# Generated by Django 3.2.18 on 2023-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMems',
            fields=[
                ('sl_id', models.AutoField(primary_key=True, serialize=False)),
                ('commem', models.CharField(max_length=100)),
                ('comprof', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SpcaMembers',
            fields=[
                ('sl_idz', models.AutoField(primary_key=True, serialize=False)),
                ('spcamems', models.CharField(default='null', max_length=100)),
                ('memsloca', models.CharField(max_length=100)),
            ],
        ),
    ]
