# Generated by Django 3.2.18 on 2023-05-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hometitle0', models.CharField(max_length=100)),
                ('homecover0', models.ImageField(blank=True, upload_to='homecovers/')),
                ('hometitle1', models.CharField(max_length=100)),
                ('homecover1', models.ImageField(blank=True, upload_to='homecovers/')),
                ('hometitle2', models.CharField(max_length=100)),
                ('homecover2', models.ImageField(blank=True, upload_to='homecovers/')),
            ],
        ),
        migrations.CreateModel(
            name='SpcaEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('coverphoto', models.ImageField(blank=True, upload_to='covers/')),
                ('image1', models.ImageField(blank=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, upload_to='images/')),
                ('image6', models.ImageField(blank=True, upload_to='images/')),
                ('image7', models.ImageField(blank=True, upload_to='images/')),
                ('image8', models.ImageField(blank=True, upload_to='images/')),
                ('image9', models.ImageField(blank=True, upload_to='images/')),
                ('image10', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
