# Generated by Django 3.2.18 on 2023-05-05 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spcacontents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='rescues')),
            ],
        ),
        migrations.CreateModel(
            name='RescuePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='rescues/')),
                ('posts', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spcacontents.rescues')),
            ],
        ),
    ]
